### ISSUE TITLE
更换bert-base-chinese

### ISSUE THREAD

**Issue by YaelLee** [mzc421/NLP#4]
你好，我这边想更换预训练的模型，改为使用bert-base-multilingual-cased，可以正常训练并且保存模型，但是运行detector时会报错：

Traceback (most recent call last):
  File "detector.py", line 220, in <module>
    model = JointIntentSlotDetector.from_pretrained(
  File "detector.py", line 27, in from_pretrained
    model = JointBert.from_pretrained(
  File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4166, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for JointBert:
        size mismatch for seq_heads.0.weight: copying a param with shape torch.Size([14, 768]) from checkpoint, the shape in current model is torch.Size([15, 768]).
        size mismatch for seq_heads.0.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([15]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
 想请教一下这是什么原因?

**Comment by mzc421** [comment]
数据纬度的问题



---- 回复的原邮件 ----
| 发件人 | Li ***@***.***> |
| 日期 | 2024年01月29日 15:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [mzc421/NLP] 更换bert-base-chinese (Issue #4) |

你好，我这边想更换预训练的模型，改为使用bert-base-multilingual-cased，可以正常训练并且保存模型，但是运行detector时会报错：

Traceback (most recent call last):
File "detector.py", line 220, in
model = JointIntentSlotDetector.from_pretrained(
File "detector.py", line 27, in from_pretrained
model = JointBert.from_pretrained(
File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
) = cls._load_pretrained_model(
File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4166, in _load_pretrained_model
raise RuntimeError(f"Error(s) in loading state_dict for {model.class.name}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for JointBert:
size mismatch for seq_heads.0.weight: copying a param with shape torch.Size([14, 768]) from checkpoint, the shape in current model is torch.Size([15, 768]).
size mismatch for seq_heads.0.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([15]).
You may consider adding ignore_mismatched_sizes=True in the model from_pretrained method.
想请教一下这是什么原因?

**Comment by mzc421** [comment]
在这个里面告诉了设置为true，来进行忽略



---- 回复的原邮件 ----
| 发件人 | Li ***@***.***> |
| 日期 | 2024年01月29日 15:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [mzc421/NLP] 更换bert-base-chinese (Issue #4) |

你好，我这边想更换预训练的模型，改为使用bert-base-multilingual-cased，可以正常训练并且保存模型，但是运行detector时会报错：

Traceback (most recent call last):
File "detector.py", line 220, in
model = JointIntentSlotDetector.from_pretrained(
File "detector.py", line 27, in from_pretrained
model = JointBert.from_pretrained(
File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
) = cls._load_pretrained_model(
File "/home/liye/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4166, in _load_pretrained_model
raise RuntimeError(f"Error(s) in loading state_dict for {model.class.name}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for JointBert:
size mismatch for seq_heads.0.weight: copying a param with shape torch.Size([14, 768]) from checkpoint, the shape in current model is torch.Size([15, 768]).
size mismatch for seq_heads.0.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([15]).
You may consider adding ignore_mismatched_sizes=True in the model from_pretrained method.
想请教一下这是什么原因?
